name: brand_measurement
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - atk-1.0=2.38.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cons=0.4.6
  - debugpy=1.8.1
  - decorator=5.1.1
  - etuples=0.3.9
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - giflib=5.2.1
  - graphite2=1.3.13
  - graphviz=9.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=8.3.0
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - joblib=1.3.2
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.26
  - libpng=1.6.43
  - librsvg=2.56.3
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libtiff=4.6.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.12.6
  - libzlib=1.2.13
  - llvm-openmp=18.1.2
  - logical-unification=0.4.6
  - matplotlib-inline=0.1.6
  - minikanren=1.0.3
  - natsort=8.4.0
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openssl=3.3.2
  - packaging=24.0
  - pandas=2.2.1
  - pandas-flavor=0.6.0
  - pandas_flavor=0.6.0
  - pango=1.52.1
  - parso=0.8.3
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - pixman=0.43.4
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyjanitor=0.27.0
  - pysocks=1.7.1
  - python=3.11.8
  - python-graphviz=0.20.3
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - setuptools=69.2.0
  - six=1.16.0
  - stack_data=0.6.2
  - threadpoolctl=3.4.0
  - tk=8.6.13
  - toolz=0.12.1
  - tornado=6.4
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xarray=2024.3.0
  - xlrd=2.0.1
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - arviz==0.17.1
      - attrs==23.2.0
      - blinker==1.7.0
      - cachetools==5.3.3
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmdstanpy==1.2.4
      - configparser==6.0.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - docopt==0.6.2
      - et-xmlfile==1.1.0
      - fastjsonschema==2.19.1
      - fastprogress==1.0.3
      - filelock==3.13.3
      - flask==3.0.2
      - fonttools==4.50.0
      - fsspec==2024.6.0
      - gevent==24.2.1
      - greenlet==3.0.3
      - h5netcdf==1.3.0
      - h5py==3.10.0
      - holidays==0.51
      - importlib-resources==6.4.0
      - itsdangerous==2.1.2
      - janitor==0.1.1
      - jax==0.4.30
      - jaxlib==0.4.30
      - jinja2==3.1.3
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - llvmlite==0.43.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mizani==0.11.1
      - ml-dtypes==0.4.0
      - mpmath==1.3.0
      - multipledispatch==1.0.0
      - nbformat==5.10.4
      - networkx==3.3
      - numba==0.60.0
      - numpyro==0.15.0
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - patsy==0.5.6
      - pillow==10.3.0
      - plotly==5.20.0
      - plotnine==0.13.3
      - prophet==1.1.5
      - pymc==5.12.0
      - pyparsing==3.1.2
      - pytensor==2.19.0
      - python-dateutil==2.9.0.post0
      - referencing==0.35.1
      - rpds-py==0.18.1
      - seaborn==0.13.2
      - shap==0.46.0
      - slicer==0.0.8
      - stanio==0.5.0
      - statsmodels==0.14.1
      - sympy==1.12.1
      - tenacity==8.2.3
      - torch==2.3.1
      - tqdm==4.66.4
      - werkzeug==3.0.2
      - wsgi-oauth2==0.2.2
      - xarray-einstats==0.7.0
      - xlsxwriter==3.2.0
      - zope-event==5.0
      - zope-interface==6.2
